import { Word, Category } from './types';

export const INITIAL_CATEGORIES: Category[] = [
  { id: '1', name: 'Umumiy', color: 'indigo' },
  { id: '2', name: 'Fe\'llar', color: 'emerald' },
  { id: '3', name: 'Sifatlar', color: 'amber' },
  { id: '4', name: 'Sayohat', color: 'rose' },
  { id: '5', name: 'Texnologiya', color: 'sky' },
];

export const INITIAL_WORDS: Word[] = [
  {
    id: 'w1',
    original: 'Challenge',
    translation: 'Qiyinchilik, chaqiriq',
    category: 'Umumiy',
    example: 'Learning a new language is a great challenge.',
    notes: 'Qiyinchilik yoki qiyin vazifa ma\'nosida keladi.',
    difficulty: 'medium',
    correctStreak: 0,
    status: 'learning',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'w2',
    original: 'Achieve',
    translation: 'Erishmoq, muvaffaqiyat qozonmoq',
    category: 'Fe\'llar',
    example: 'You can achieve anything with hard work.',
    notes: 'Maqsadga erishish ma\'nosida.',
    difficulty: 'medium',
    correctStreak: 0,
    status: 'learning',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'w3',
    original: 'Persistent',
    translation: 'Tirishqoq, qat\'iyatli',
    category: 'Sifatlar',
    example: 'She was persistent in chasing her dreams.',
    notes: 'Taslim bo\'lmaydigan, doimiy harakatdagi odam.',
    difficulty: 'hard',
    correctStreak: 0,
    status: 'learning',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'w4',
    original: 'Opportunity',
    translation: 'Imkoniyat, qulay sharoit',
    category: 'Umumiy',
    example: 'This project is a big opportunity for us.',
    notes: 'Imkon, qulay fursat.',
    difficulty: 'easy',
    correctStreak: 0,
    status: 'learning',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'w5',
    original: 'Improve',
    translation: 'Yaxshilamoq, rivojlantirmoq',
    category: 'Fe\'llar',
    example: 'I want to improve my English speaking skills.',
    notes: 'Rivojlantirmoq, darajasini oshirmoq.',
    difficulty: 'easy',
    correctStreak: 0,
    status: 'learning',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'w6',
    original: 'Destination',
    translation: 'Manzil, boradigan joy',
    category: 'Sayohat',
    example: 'We finally reached our destination after a long flight.',
    difficulty: 'medium',
    correctStreak: 0,
    status: 'learning',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'w7',
    original: 'Innovation',
    translation: 'Yangi ixtiro, innovatsiya',
    category: 'Texnologiya',
    example: 'Technological innovation drives the economy forward.',
    difficulty: 'hard',
    correctStreak: 0,
    status: 'learning',
    createdAt: new Date().toISOString(),
  }
];
